global:
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: true
env:
  GO_ENV: development
  DATABASE_URL: mongodb://127.0.0.1:27017/shortit?directConnection=true
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379
  REDIS_PASSWORD: ""
  SHORTIT_REDIRECT_HOST: http://127.0.0.1
mongodb:
  image:
    registry: docker.io
    repository: dlavrenuek/bitnami-mongodb-arm
    tag: "8.0.4"
    digest: ""
  auth:
    username: shortit
    password: flinstones
    rootPassword: root12flinstones

redis:
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: "7.2"
    pullPolicy: IfNotPresent
  auth:
    enabled: false
  architecture: standalone # Can be "standalone" or "replication"
  master:
    persistence:
      enabled: true
      size: 8Gi
  metrics:
    enabled: false

service:
  name: service-generate
  image:
    registry: localhost:5001
    repository: service-generate
    tag: latest
    pullPolicy: IfNotPresent
  port: 8001
  service:
    port: 8001
  replicas: 1

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
