apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc }}

apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "shortit.dockerconfig" . | b64enc | quote }}