apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-generate
spec:
  selector:
    app: service-generate
  ports:
    - protocol: TCP
      port: {{ .Values.service.service.port }}
      targetPort: {{ .Values.service.port }}
