apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-generate
spec:
  selector:
    app: service-generate
  ports:
    - protocol: TCP
      port: {{ .Values.serviceGenerate.service.port }}
      targetPort: {{ .Values.serviceGenerate.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-redirect
spec:
  selector:
    app: service-redirect
  ports:
    - protocol: TCP
      port: {{ .Values.serviceRedirect.service.port }}
      targetPort: {{ .Values.serviceRedirect.port }}
